# Generated by Django 4.2.1 on 2023-05-26 08:01

import core.post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to=core.post.models.user_directory_path),
        ),
    ]
