# Generated by Django 4.2.1 on 2023-05-26 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_post', '0002_post_post_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
